online-time-money: 5
online-time-minutes: 5

database:
  host: 192.168.2.55
  port: 3306
  database: minecraft
  username: admin
  password: Gaborka11

email:
  host: mail.sativus.uk
  port: 587
  from: noreply_spigot@sativus.uk
  username: ubuntu
  password: Gaborka11